services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diavgeia_notifier
    restart: unless-stopped
    volumes:
      - ./options.json:/app/options.json
      - ./output.json:/app/output.json